version: "3"
services:
  tauri:
    build: .
    working_dir: /workdir
    command: sleep infinity
    environment:
      - HOME=/root
      - no_proxy=127.0.0.1,localhost
    volumes:
      - ~/.gitconfig:/home/root/.gitconfig
      - ../:/workdir
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/dri:/dev/dri
    network_mode: "host"
    extra_hosts:
      - tauri:127.0.1.1